name: Test & Upload Debug APK Artifact

on:
  push:
    branches: '*'
    
jobs:
  build:

    runs-on: ubuntu-latest
    environment: build_environment

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8  

    - name: Add executable permission to gradle wrapper
      run: chmod +x ./gradlew

    - name: Test with Gradle
      run: ./gradlew testDebugUnitTest

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace
      env:
          CLIST_API_KEY: ${{ secrets.CLIST_API_KEY }}
    
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
